#!/bin/sh

rm -rf limine
git clone https://github.com/limine-bootloader/limine.git --branch=v7.x-binary --depth=1
make -C limine

mkdir -p ovmf
cd ovmf && curl -Lo OVMF.fd https://retrage.github.io/edk2-nightly/bin/RELEASEX64_OVMF.fd